### ISSUE TITLE
Read from memory

### ISSUE THREAD

**Issue by cognitus** [inspirum/xml-php#2]
## Detailed description

Hello! 
this is my first time using php for manipulating xml, and i look your library and looks pretty good... I want to know if is posible read xml from memory? 
for example  xml file from file_get_contents('myfile.xml');

and if you have planed deal with xml sign?

**Comment by tomas-novotny** [comment]
Hello

The [`Reader`](https://github.com/inspirum/xml-php/blob/master/src/Reader/Reader.php) uses a native [`XMLReader`](https://www.php.net/manual/en/book.xmlreader.php) that (by design) can only iterate over a file. But you can always create some temporary file from XML content.

But you can certainly load an XML file or its contents into a [`Document`](https://github.com/inspirum/xml-php/blob/master/src/Builder/Document.php) using [`DocumentFactory::createForFile()`](https://github.com/inspirum/xml-php/blob/master/src/Builder/DocumentFactory.php#L20) or [`DocumentFactory::createForContent()`](https://github.com/inspirum/xml-php/blob/master/src/Builder/DocumentFactory.php#L27) which can then be casted to an array using the [`toArray()`](https://github.com/inspirum/xml-php/blob/master/src/Builder/BaseNode.php#LL269C5-L269C5) method.



I don't know exactly what you need to do to be more helpful.


If you are asking about signing XML Documents with digital signatures, then this library does not implement it. But there are other libraries that do this.
